- backend/users/views.py
> test commit

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/Logo.tsx
- frontend/src/pages/MainPage.tsx
- frontend/src/styles/LayoutStyle.css.ts
- frontend/vite.config.ts
fix: vanilla-extract config 설정
> fix: vanilla-extract config 설정

- backend/config/base.py
- backend/config/urls.py
- backend/gpt/admin.py
- backend/gpt/apps.py
- backend/gpt/models.py
- backend/gpt/tests.py
- backend/gpt/urls.py
- backend/gpt/views.py
-gpt 한테 퀴즈 5개  받아서 json형태로 res 클라이언트한테 보내준다
closed #41
> feat:gpt 질문 받는 기능

- frontend/src/components/appbar/AppBar.css
- frontend/src/pages/QuizPage.tsx
- frontend/src/pages/UserUpdatePage.tsx
- frontend/src/routes/index.tsx
- frontend/src/styles/AppBar.css.ts
- frontend/src/styles/LevelPage.css.ts
> [feat/3ENG-32] 스타일 변경

- backend/gpt/views.py
-gpt에서 회원답변과 gpt질문을 5개씩 넣어주면 피드백과 점수를 반환 시켜주는 기능
cloes #44
> feat:gpt 피드백 기능

- backend/config/base.py
- backend/config/urls.py
- backend/quizs/models.py
- backend/quizs/serializers.py
- backend/quizs/urls.py
- backend/quizs/views.py
> gpt질문과 회원답변 저장하는 기능

- frontend/src/components/ReviewComponent.tsx
- frontend/src/pages/MyLearningPage.tsx
- frontend/src/styles/MyLearningPage.css.ts
learning page 기본 틀 완성
closes #34
> feat:나의 학습공간 틀 완성

- frontend/src/pages/MyLearningPage.tsx
- frontend/src/styles/MyLearningPage.css.ts
MyLearningPage.tsx css 변수명 수정
MyLearningPage.css.ts css 변수명 및 위치 값 수정
close #58
> fix: 나의 학습공간 페이지 css 위치값 수정 및 css 변수명 수정

- frontend/src/components/appbar/AppBar.css
- frontend/src/components/appbar/AppBar.tsx
AppBar.css 메뉴 컨테이너 수정
AppBar.tsx 라우터 설정 및 메뉴 이름 등록
> appbar css 수정 및 메뉴 이름 router 등록

- frontend/src/pages/QuizPage.tsx
- frontend/src/styles/QuizStyle.css.ts
- package-lock.json
> [Feat/32] quiz페이지 디자인

- backend/config/base.py
- backend/feedbacks/serializers.py
- backend/quizs/serializers.py
- backend/users/views.py
- 임시 쿠키로 저장 안하고 데이터로 access_token 및 refresh_token 보내는 형식으로 바꿈
close #66
> fix:로그인 기능 버그 수정

- backend/users/views.py
- 로그아웃 할 때 토큰 사젝 로직 추가
closes #68
> fix:로그아웃 할 때 토큰 삭제

- backend/users/urls.py
- backend/users/views.py
- 특정 유저 아이디 값을 가져와서 질문 답변 피드백 점수 날짜 가져오기 기능
> feat:특정 유저 질문 답변 피드백 점수 가져오는 기능

- frontend/src/pages/ResultDetail.tsx
- frontend/src/pages/ResultPage.tsx
- frontend/src/styles/ResultStyle.css.ts
- 결과페이지에서 상세보기 클릭 시 카드 뒤집는 효과 구현 
close #73
> [feat/3ENG-73] feat: 결과페이지 점수/피드백 카드 뒤집기 기능

- .vscode/settings.json
- frontend/src/store/useAuth.tsx
> [feat/3ENG-76] zustand store 생성

- frontend/src/components/ReviewComponent.tsx
- frontend/src/pages/MyLearningPage.tsx
- frontend/src/styles/MyLearningPage.css.ts
MyLearningPage.css.ts : 반응형, 크기
MyLearningPage.tsx: div 추가
> fix: 나의 학습공간 페이지 css 수정

- backend/config/base.py
- backend/config/urls.py
- backend/graph/admin.py
- backend/graph/apps.py
- backend/graph/models.py
- backend/graph/tests.py
- backend/graph/usrls.py
- backend/graph/views.py
- 월별, 주별, 일별 평균 데이터 GET RESTAPI 기능
close #82
> 데이터 시각화 할 데이터 추출 기능

- frontend/src/App.tsx
- frontend/src/api/axios.tsx
- frontend/src/components/DuplicateInput.tsx
- frontend/src/components/Input.tsx
- frontend/src/pages/Auth.tsx
- frontend/src/styles/LoginStyle.css.ts
- frontend/src/styles/index.css
- 로그인/회원가입 유효성 검증 추가
- 회원가입 시 이메일,닉네임 중복확인버튼 css 및 기능 추가
> [fix/3ENG-89]

- backend/config/base.py
- backend/users/models.py
- backend/users/urls.py
- backend/users/views.py
- 이메일로 비밀번호 찾기 후 이메일 발송 기능
- 발송한 링크 클릭후 비밀번호 초기화 및 새로운 비밀번호 발급 기능
close #94
> feat:유저 비밀번호 찾기(초기화) 기능

- frontend/src/pages/QuizPage.tsx
- frontend/src/styles/QuizStyle.css.ts
- 문제 하나씩 보여주기
- 이전, 다음, 제출 버튼 기능
- 제출버튼 클릭 시 결과 페이지로 이동
> [fix/3ENG-98] 퀴즈페이지 오류 수정

- backend/gpt/views.py
> fix:gpt 질문 기능 수정 1차

- frontend/src/components/DuplicateInput.tsx
- frontend/src/pages/Auth.tsx
- frontend/src/styles/LoginStyle.css.ts
- 유효성 조건 충족 시, input 창 아래에 뜨는 오류메시지 사라지게 수정
- 회원가입 성공 시 바로 로그인 창으로 이동하도록 수정
- 이메일,닉네임이 유효성 조건을 충족할때에만 중복확인 버튼 활성화
- 중복 확인버튼 비활성화/활성화시 색상 구분
> [fix/3ENG-100] 로그인/회원가입페이지 오류메시지 및 중복확인 버튼 기능,css 수정

- frontend/src/pages/QuizPage.tsx
- prev 버튼클릭 시 이전 답변 유지 및 수정 기능
> [fix/3ENG-107] prev 버튼클릭 시 이전 답변 유지 및 수정 기능

- frontend/src/components/ReviewComponent.tsx
- frontend/src/components/appbar/AppBar.tsx
- frontend/src/pages/LevelPage.tsx
- frontend/src/pages/MyLearningPage.tsx
- frontend/src/pages/WeekPage.tsx
- frontend/src/routes/index.tsx
- frontend/src/styles/MyLearningPage.css.ts
WeekPage.tsx 코드 수정
MyLearningPage.tsx, ReviewComponent.tsx 클릭 버그 수정
> fix: week 페이지 수정 및 나의 학습공간 클릭 버그 수정

- frontend/src/components/Input.tsx
- frontend/src/components/PasswordModal.tsx
- frontend/src/pages/Auth.tsx
- frontend/src/styles/LoginStyle.css.ts
- frontend/src/styles/PasswordRest.css.ts
> [feat/3ENG-112] 비밀번호 재설정 모달 기능

- frontend/src/api/axios.tsx
- frontend/src/components/Input.tsx
- frontend/src/pages/UserUpdatePage.tsx
> fix: 회원정보수정 페이지 api 코드 수정

- frontend/src/components/PasswordModal.tsx
- frontend/src/pages/Auth.tsx
- frontend/src/pages/UserUpdatePage.tsx
> fix: api요청코드 수정

- frontend/src/components/appbar/AppBar.css
- frontend/src/components/appbar/AppBar.tsx
feat: appbar 유저정보 api연동
appbar.tsx, appbar.css 유저 이미지 수정 및 코드 수정
> feat: appbar 유저정보 api연동

- backend/config/base.py
- backend/static/complete.css
- backend/static/confirm.css
- backend/templates/password_reset_complete.html
- backend/templates/password_reset_confirm.html
- backend/users/urls.py
- backend/users/views.py
> feat:비밀번호 찾기 장고 html 간단한 커스텀 추후에 이쁘게 꾸밀 예정

- frontend/src/pages/Auth.tsx
- 첫 화면을 회원가입화면에서 로그인화면으로 수정
- 로그인 눌렀을때 오류메시지 나오는거 수정
> [fix/3ENG-126] 로그인/회원가입페이지 코드 수정

- frontend/src/api/axios.tsx
> feat: 리프레시 토큰을 활용하여 토큰 갱신 기능(수정 가능성 있음)

- backend/config/base.py
> settings 오타 수정

- frontend/src/Components.tsx
- frontend/src/pages/Auth.tsx
- frontend/src/pages/UserUpdatePage.tsx
- frontend/src/styles/LoginStyle.css.ts
- frontend/src/styles/UserUpdateStyle.css.ts
- user-update 페이지 반응형 css 수정
- 500px~768px 사이에 프로필 이미지와 닉네임이 깨져서 570px으로 진행하였음
> [fix/3ENG-135] user-update 페이지 반응형 css 수정

- frontend/src/components/Logo.tsx
- frontend/src/pages/MainPage.tsx
- frontend/src/styles/ButtonStyle.css.ts
- frontend/src/styles/FontAnimate.css
- frontend/src/styles/LayoutStyle.css.ts
- frontend/src/styles/MainTextStyle.css
- frontend/src/styles/index.css
> [fix/3ENG-148] main 페이지 반응형 및 css 수정

- frontend/src/hooks/useHorizontalScroll.tsx
- frontend/src/pages/LevelPage.tsx
- frontend/src/styles/LevelPage.css.ts
LevelPage.css.ts: css 수정
LevelPage.tsx: 구조 수정
> fix:level페이지 스크롤 반응형으로 변경(수정 가능성 있음)

- frontend/src/pages/Auth.tsx
- frontend/src/pages/QuizPage.tsx
- frontend/src/pages/ResultPage.tsx
- frontend/src/styles/LoginStyle.css.ts
- quiz데이터 받아오는 함수
- 로그인/회원가입 페이지 반응형 css
> [fix/3ENG-150]quiz데이터 받아오는 함수, 로그인 반응형 css

- frontend/src/components/appbar/AppBar.tsx
- frontend/src/pages/QuizPage.tsx
- frontend/src/pages/ResultPage.tsx
- frontend/src/pages/UserUpdatePage.tsx
> fix: 백엔드 연결코드 수정

- .vscode/settings.json
- frontend/src/components/QuizInput.tsx
- frontend/src/pages/QuizPage.tsx
- frontend/src/pages/ResultPage.tsx
- frontend/src/pages/UserUpdatePage.tsx
- frontend/src/styles/QuizStyle.css.ts
- frontend/src/styles/UserUpdateStyle.css.ts
- 답변 Input 상태를 useState 에서 useRef로 변경
- 답변 Input 컴포넌트 분리
- userUpdate 페이지 useEffect종속성 배열 수정
- userUpdate 페이지 css 변수명 변경
> [fix/3ENG-178] quiz페이지 리렌더링 관리 및 컴포넌트 분리

- backend/gpt/management/commands/closepoll.py
> feat: 회원 탈퇴 기능

- frontend/src/components/QuizAnswer.tsx
- frontend/src/components/QuizInput.tsx
- frontend/src/pages/ResultPage.tsx
- quiz 답변 컴포넌트 분리 
- result 페이지 get함수 api 엔드포인트 수정
> [fix/3ENG-182] quiz 답변 컴포넌트 분리 및 result 페이지 get함수 api 엔드포인트 수정

- backend/config/base.py
> 비밀번호 규칙 수정

- frontend/src/components/LogIn.tsx
- frontend/src/pages/UserUpdatePage.tsx
- 회원탈퇴 요청 기능
- 탈퇴한 회원 로그인 시, 30일동안 '이미 탈퇴한 회원입니다' 메시지 알림
> [feat/3ENG-188] 회원탈퇴기능

- backend/users/urls.py
- backend/users/views.py
> feat: 요일별 유저 토탈 점수 가져오기 기능

- frontend/src/pages/NotFoundPage.tsx
- frontend/src/routes/PrivateRoute.tsx
- frontend/src/routes/PublicRoute.tsx
- frontend/src/routes/index.tsx
- frontend/src/styles/NotFoundPage.css.ts
- frontend/src/utils/isLogin.tsx
- 토큰유무에 따른 페이지 라우터 설정
- 올바르지않은 url입력 시 NotFoundPage 설정
> [feat/3ENG-192] 토큰유무에따른 라우터 설정

- frontend/src/components/LogIn.tsx
- frontend/src/components/PasswordModal.tsx
- frontend/src/styles/LoginStyle.css.ts
- frontend/src/styles/PasswordRest.css.ts
- 비밀번호 재설정 오류메시지 수정
- 메일 전송 시, 버튼 비활성화 및 alert설정
- 등록되지 않은 이메일 작성 시 alert
- 버튼 비활성화 시 css 수정
- 비밀번호 모달 최소너비 지정
> [fix/3ENG-196] 비밀번호 재설정 오류메시지 수정, 메일 전송 후 버튼 비활성화, 최소너비 지정

- backend/config/base.py
- backend/users/urls.py
- backend/users/views.py
> feat: 비밀번호 초기화 특수문자 유효성 기능

- frontend/src/components/DuplicateInput.tsx
- frontend/src/components/Input.tsx
- frontend/src/components/LogIn.tsx
- frontend/src/components/SignUp.tsx
- frontend/src/styles/LoginStyle.css.ts
- frontend/src/utils/fetchValidation.tsx
- frontend/src/utils/keyDownHandler.tsx
- 유효성확인하는 state 삭제(오류메시지 상태로 같이 사용)
- 닉네임,이메일 중복확인 시 submit 호출되는 오류 수정
- 닉네임, 이메일 중복확인 함수 utils로 분리, 및 재사용
- 로그인, 회원가입 keyDown 추가
- keyDown 함수 utils로 분리 및 재사용
닉네임/이메일 입력 후 엔터 시 중복확인 버튼 / 비밀번호 입력 후 엔터 시 로그인/회원가입 버튼 클릭되도록
- 로그인/회원가입 화면 줄어들시 transition:none, 버튼 글자 크기 수정
> [fix/3ENG-201] auth페이지 기능추가 및 코드/css 수정

- frontend/src/components/QuizAnswer.tsx
- frontend/src/components/QuizInput.tsx
- frontend/src/pages/QuizPage.tsx
- input에서 엔터 시 NEXT 버튼 호출하도록 KeyDown 이벤트 추가
- 문제 넘어간 후 Input 자동 포커스되도록 기능 추가
> [fix/3ENG-203] input에서 엔터 시 다음문제, Input autoFocus기능 추가

- frontend/src/components/appbar/AppBar.css
- frontend/src/components/appbar/AppBar.tsx
- frontend/src/styles/FontAnimate.css
- frontend/src/styles/LevelPage.css.ts
- frontend/src/styles/QuizStyle.css.ts
- frontend/src/styles/index.css
- 메인페이지 로고폰트 수정
- 앱바 로고 사이즈 수정
- 메인로고 폰트 수정
> [fix]3ENG-205] 메인 폰트 수정
